name: "✨ Feature Request"
description: "Propose a new feature or enhancement"
labels: ["type: feature"]
assignees: ["sukki-codes"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What & Why
      placeholder: "무엇을 왜 만드는지"
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: Checklist
      value: |
        - [ ]
